import AuthProvider from "@/components/auth-provider";
import StoreProvider from "@/lib/redux";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Course Pilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <AuthProvider>{children}</AuthProvider>
    </StoreProvider>
  );
}
